export type Sector = "Insurance" | "Asset Management" | "Sell-Side";
export type AccountStatus = "active" | "inactive";

export interface Customer {
  id: string;
  name: string;
  headcount: number;
  headcountUS: number;
  headcountIndia: number;
  monthlyRevenue: number;
  monthlyCosts: number;
  /** Cumulative delivery cost since the customer relationship began (mock). */
  cumulativeCostsSinceInception: number;
  /** One-time cost attributed to the most recently closed project phase (mock). */
  mostRecentProjectCost: number;
  pipelineValue: number;
  pipelineStatus: "none" | "early" | "negotiating" | "closing";
  industry: string;
  sector: Sector;
  accountStatus: AccountStatus;
}

export interface Expense {
  id: string;
  category: string;
  description: string;
  amount: number;
  type: "company" | "customer";
  customerId?: string;
}

export const SECTORS: Sector[] = ["Insurance", "Asset Management", "Sell-Side"];

export const customers: Customer[] = [
  {
    id: "1",
    name: "BlackRock",
    headcount: 45,
    headcountUS: 30,
    headcountIndia: 15,
    monthlyRevenue: 2850000,
    monthlyCosts: 1425000,
    cumulativeCostsSinceInception: 51800000,
    mostRecentProjectCost: 2400000,
    pipelineValue: 1200000,
    pipelineStatus: "negotiating",
    industry: "Asset Management",
    sector: "Asset Management",
    accountStatus: "active",
  },
  {
    id: "2",
    name: "Goldman Sachs",
    headcount: 38,
    headcountUS: 33,
    headcountIndia: 5,
    monthlyRevenue: 2400000,
    monthlyCosts: 1140000,
    cumulativeCostsSinceInception: 44100000,
    mostRecentProjectCost: 1980000,
    pipelineValue: 800000,
    pipelineStatus: "closing",
    industry: "Investment Banking",
    sector: "Sell-Side",
    accountStatus: "active",
  },
  {
    id: "3",
    name: "Chubb",
    headcount: 32,
    headcountUS: 19,
    headcountIndia: 13,
    monthlyRevenue: 2100000,
    monthlyCosts: 966000,
    cumulativeCostsSinceInception: 35200000,
    mostRecentProjectCost: 1650000,
    pipelineValue: 0,
    pipelineStatus: "none",
    industry: "P&C Insurance",
    sector: "Insurance",
    accountStatus: "active",
  },
  {
    id: "4",
    name: "Progressive",
    headcount: 28,
    headcountUS: 16,
    headcountIndia: 12,
    monthlyRevenue: 1900000,
    monthlyCosts: 855000,
    cumulativeCostsSinceInception: 28900000,
    mostRecentProjectCost: 920000,
    pipelineValue: 500000,
    pipelineStatus: "early",
    industry: "P&C Insurance",
    sector: "Insurance",
    accountStatus: "inactive",
  },
  {
    id: "5",
    name: "Evercore",
    headcount: 25,
    headcountUS: 22,
    headcountIndia: 3,
    monthlyRevenue: 1750000,
    monthlyCosts: 787500,
    cumulativeCostsSinceInception: 24800000,
    mostRecentProjectCost: 1100000,
    pipelineValue: 650000,
    pipelineStatus: "negotiating",
    industry: "Investment Banking",
    sector: "Sell-Side",
    accountStatus: "active",
  },
  {
    id: "6",
    name: "JPMorgan",
    headcount: 42,
    headcountUS: 35,
    headcountIndia: 7,
    monthlyRevenue: 2600000,
    monthlyCosts: 1300000,
    cumulativeCostsSinceInception: 58200000,
    mostRecentProjectCost: 3100000,
    pipelineValue: 0,
    pipelineStatus: "none",
    industry: "Investment Banking",
    sector: "Sell-Side",
    accountStatus: "active",
  },
  {
    id: "7",
    name: "Vanguard",
    headcount: 35,
    headcountUS: 22,
    headcountIndia: 13,
    monthlyRevenue: 2200000,
    monthlyCosts: 1100000,
    cumulativeCostsSinceInception: 39500000,
    mostRecentProjectCost: 1750000,
    pipelineValue: 450000,
    pipelineStatus: "early",
    industry: "Asset Management",
    sector: "Asset Management",
    accountStatus: "active",
  },
  {
    id: "8",
    name: "State Street",
    headcount: 22,
    headcountUS: 14,
    headcountIndia: 8,
    monthlyRevenue: 1500000,
    monthlyCosts: 660000,
    cumulativeCostsSinceInception: 27100000,
    mostRecentProjectCost: 1420000,
    pipelineValue: 900000,
    pipelineStatus: "closing",
    industry: "Asset Servicing",
    sector: "Asset Management",
    accountStatus: "active",
  },
  {
    id: "9",
    name: "Invesco",
    headcount: 18,
    headcountUS: 11,
    headcountIndia: 7,
    monthlyRevenue: 1200000,
    monthlyCosts: 540000,
    cumulativeCostsSinceInception: 19600000,
    mostRecentProjectCost: 780000,
    pipelineValue: 350000,
    pipelineStatus: "negotiating",
    industry: "Asset Management",
    sector: "Asset Management",
    accountStatus: "active",
  },
  {
    id: "10",
    name: "Fidelity",
    headcount: 20,
    headcountUS: 12,
    headcountIndia: 8,
    monthlyRevenue: 1350000,
    monthlyCosts: 607500,
    cumulativeCostsSinceInception: 21800000,
    mostRecentProjectCost: 890000,
    pipelineValue: 0,
    pipelineStatus: "none",
    industry: "Asset Management",
    sector: "Asset Management",
    accountStatus: "active",
  },
  {
    id: "11",
    name: "MetLife",
    headcount: 24,
    headcountUS: 15,
    headcountIndia: 9,
    monthlyRevenue: 1600000,
    monthlyCosts: 720000,
    cumulativeCostsSinceInception: 25900000,
    mostRecentProjectCost: 980000,
    pipelineValue: 280000,
    pipelineStatus: "early",
    industry: "Life Insurance",
    sector: "Insurance",
    accountStatus: "active",
  },
  {
    id: "12",
    name: "Prudential Financial",
    headcount: 15,
    headcountUS: 9,
    headcountIndia: 6,
    monthlyRevenue: 980000,
    monthlyCosts: 441000,
    cumulativeCostsSinceInception: 15800000,
    mostRecentProjectCost: 520000,
    pipelineValue: 0,
    pipelineStatus: "none",
    industry: "Life Insurance",
    sector: "Insurance",
    accountStatus: "inactive",
  },
  {
    id: "13",
    name: "AIG",
    headcount: 17,
    headcountUS: 10,
    headcountIndia: 7,
    monthlyRevenue: 1100000,
    monthlyCosts: 495000,
    cumulativeCostsSinceInception: 17700000,
    mostRecentProjectCost: 760000,
    pipelineValue: 420000,
    pipelineStatus: "negotiating",
    industry: "Multiline Insurance",
    sector: "Insurance",
    accountStatus: "active",
  },
  {
    id: "14",
    name: "T. Rowe Price",
    headcount: 30,
    headcountUS: 19,
    headcountIndia: 11,
    monthlyRevenue: 2000000,
    monthlyCosts: 900000,
    cumulativeCostsSinceInception: 33400000,
    mostRecentProjectCost: 1880000,
    pipelineValue: 1500000,
    pipelineStatus: "closing",
    industry: "Asset Management",
    sector: "Asset Management",
    accountStatus: "active",
  },
  {
    id: "15",
    name: "Morgan Stanley",
    headcount: 26,
    headcountUS: 21,
    headcountIndia: 5,
    monthlyRevenue: 1800000,
    monthlyCosts: 810000,
    cumulativeCostsSinceInception: 30500000,
    mostRecentProjectCost: 1550000,
    pipelineValue: 600000,
    pipelineStatus: "early",
    industry: "Investment Banking",
    sector: "Sell-Side",
    accountStatus: "active",
  },
  {
    id: "16",
    name: "Citigroup",
    headcount: 19,
    headcountUS: 14,
    headcountIndia: 5,
    monthlyRevenue: 1250000,
    monthlyCosts: 562500,
    cumulativeCostsSinceInception: 21200000,
    mostRecentProjectCost: 990000,
    pipelineValue: 0,
    pipelineStatus: "none",
    industry: "Investment Banking",
    sector: "Sell-Side",
    accountStatus: "active",
  },
  {
    id: "17",
    name: "Barclays",
    headcount: 12,
    headcountUS: 8,
    headcountIndia: 4,
    monthlyRevenue: 780000,
    monthlyCosts: 351000,
    cumulativeCostsSinceInception: 12400000,
    mostRecentProjectCost: 410000,
    pipelineValue: 200000,
    pipelineStatus: "early",
    industry: "Investment Banking",
    sector: "Sell-Side",
    accountStatus: "inactive",
  },
  {
    id: "18",
    name: "Jefferies",
    headcount: 14,
    headcountUS: 11,
    headcountIndia: 3,
    monthlyRevenue: 920000,
    monthlyCosts: 414000,
    cumulativeCostsSinceInception: 14600000,
    mostRecentProjectCost: 630000,
    pipelineValue: 0,
    pipelineStatus: "none",
    industry: "Investment Banking",
    sector: "Sell-Side",
    accountStatus: "active",
  },
  {
    id: "19",
    name: "Moelis & Company",
    headcount: 21,
    headcountUS: 17,
    headcountIndia: 4,
    monthlyRevenue: 1400000,
    monthlyCosts: 630000,
    cumulativeCostsSinceInception: 22100000,
    mostRecentProjectCost: 870000,
    pipelineValue: 380000,
    pipelineStatus: "negotiating",
    industry: "Investment Banking",
    sector: "Sell-Side",
    accountStatus: "active",
  },
  {
    id: "20",
    name: "UBS",
    headcount: 23,
    headcountUS: 16,
    headcountIndia: 7,
    monthlyRevenue: 1550000,
    monthlyCosts: 697500,
    cumulativeCostsSinceInception: 24800000,
    mostRecentProjectCost: 1020000,
    pipelineValue: 0,
    pipelineStatus: "none",
    industry: "Investment Banking",
    sector: "Sell-Side",
    accountStatus: "active",
  },
  {
    id: "21",
    name: "UnitedHealth Group",
    headcount: 29,
    headcountUS: 18,
    headcountIndia: 11,
    monthlyRevenue: 1950000,
    monthlyCosts: 877500,
    cumulativeCostsSinceInception: 31800000,
    mostRecentProjectCost: 1340000,
    pipelineValue: 750000,
    pipelineStatus: "closing",
    industry: "Health Insurance",
    sector: "Insurance",
    accountStatus: "active",
  },
  {
    id: "22",
    name: "Elevance Health",
    headcount: 16,
    headcountUS: 10,
    headcountIndia: 6,
    monthlyRevenue: 1050000,
    monthlyCosts: 472500,
    cumulativeCostsSinceInception: 16800000,
    mostRecentProjectCost: 580000,
    pipelineValue: 0,
    pipelineStatus: "none",
    industry: "Health Insurance",
    sector: "Insurance",
    accountStatus: "active",
  },
  {
    id: "23",
    name: "Humana",
    headcount: 18,
    headcountUS: 11,
    headcountIndia: 7,
    monthlyRevenue: 1200000,
    monthlyCosts: 540000,
    cumulativeCostsSinceInception: 18900000,
    mostRecentProjectCost: 710000,
    pipelineValue: 320000,
    pipelineStatus: "early",
    industry: "Health Insurance",
    sector: "Insurance",
    accountStatus: "active",
  },
  {
    id: "24",
    name: "Allstate",
    headcount: 27,
    headcountUS: 14,
    headcountIndia: 13,
    monthlyRevenue: 1850000,
    monthlyCosts: 832500,
    cumulativeCostsSinceInception: 27600000,
    mostRecentProjectCost: 1180000,
    pipelineValue: 550000,
    pipelineStatus: "negotiating",
    industry: "P&C Insurance",
    sector: "Insurance",
    accountStatus: "inactive",
  },
  {
    id: "25",
    name: "Travelers",
    headcount: 24,
    headcountUS: 15,
    headcountIndia: 9,
    monthlyRevenue: 1620000,
    monthlyCosts: 729000,
    cumulativeCostsSinceInception: 24100000,
    mostRecentProjectCost: 940000,
    pipelineValue: 0,
    pipelineStatus: "none",
    industry: "P&C Insurance",
    sector: "Insurance",
    accountStatus: "active",
  },
  {
    id: "26",
    name: "Marsh McLennan",
    headcount: 22,
    headcountUS: 13,
    headcountIndia: 9,
    monthlyRevenue: 1480000,
    monthlyCosts: 666000,
    cumulativeCostsSinceInception: 22900000,
    mostRecentProjectCost: 860000,
    pipelineValue: 0,
    pipelineStatus: "none",
    industry: "Insurance Brokerage",
    sector: "Insurance",
    accountStatus: "active",
  },
  {
    id: "27",
    name: "Franklin Templeton",
    headcount: 11,
    headcountUS: 6,
    headcountIndia: 5,
    monthlyRevenue: 720000,
    monthlyCosts: 324000,
    cumulativeCostsSinceInception: 11200000,
    mostRecentProjectCost: 480000,
    pipelineValue: 250000,
    pipelineStatus: "negotiating",
    industry: "Asset Management",
    sector: "Asset Management",
    accountStatus: "active",
  },
  {
    id: "28",
    name: "AllianceBernstein",
    headcount: 8,
    headcountUS: 5,
    headcountIndia: 3,
    monthlyRevenue: 520000,
    monthlyCosts: 234000,
    cumulativeCostsSinceInception: 7800000,
    mostRecentProjectCost: 290000,
    pipelineValue: 180000,
    pipelineStatus: "early",
    industry: "Asset Management",
    sector: "Asset Management",
    accountStatus: "active",
  },
  {
    id: "29",
    name: "Wellington Management",
    headcount: 15,
    headcountUS: 11,
    headcountIndia: 4,
    monthlyRevenue: 980000,
    monthlyCosts: 441000,
    cumulativeCostsSinceInception: 14200000,
    mostRecentProjectCost: 670000,
    pipelineValue: 0,
    pipelineStatus: "none",
    industry: "Asset Management",
    sector: "Asset Management",
    accountStatus: "active",
  },
  {
    id: "30",
    name: "PIMCO",
    headcount: 13,
    headcountUS: 8,
    headcountIndia: 5,
    monthlyRevenue: 850000,
    monthlyCosts: 382500,
    cumulativeCostsSinceInception: 12800000,
    mostRecentProjectCost: 720000,
    pipelineValue: 400000,
    pipelineStatus: "early",
    industry: "Fixed Income AM",
    sector: "Asset Management",
    accountStatus: "active",
  },
  {
    id: "31",
    name: "Schroders",
    headcount: 10,
    headcountUS: 4,
    headcountIndia: 6,
    monthlyRevenue: 650000,
    monthlyCosts: 292500,
    cumulativeCostsSinceInception: 9400000,
    mostRecentProjectCost: 510000,
    pipelineValue: 300000,
    pipelineStatus: "closing",
    industry: "Asset Management",
    sector: "Asset Management",
    accountStatus: "inactive",
  },
  {
    id: "32",
    name: "Piper Sandler",
    headcount: 9,
    headcountUS: 8,
    headcountIndia: 1,
    monthlyRevenue: 580000,
    monthlyCosts: 261000,
    cumulativeCostsSinceInception: 8200000,
    mostRecentProjectCost: 360000,
    pipelineValue: 220000,
    pipelineStatus: "negotiating",
    industry: "Investment Banking",
    sector: "Sell-Side",
    accountStatus: "active",
  },
  {
    id: "33",
    name: "Stifel",
    headcount: 7,
    headcountUS: 6,
    headcountIndia: 1,
    monthlyRevenue: 450000,
    monthlyCosts: 202500,
    cumulativeCostsSinceInception: 6100000,
    mostRecentProjectCost: 240000,
    pipelineValue: 0,
    pipelineStatus: "none",
    industry: "Investment Banking",
    sector: "Sell-Side",
    accountStatus: "active",
  },
  {
    id: "34",
    name: "William Blair",
    headcount: 13,
    headcountUS: 12,
    headcountIndia: 1,
    monthlyRevenue: 850000,
    monthlyCosts: 382500,
    cumulativeCostsSinceInception: 11500000,
    mostRecentProjectCost: 590000,
    pipelineValue: 400000,
    pipelineStatus: "early",
    industry: "Investment Banking",
    sector: "Sell-Side",
    accountStatus: "active",
  },
  {
    id: "35",
    name: "BMO Capital Markets",
    headcount: 11,
    headcountUS: 7,
    headcountIndia: 4,
    monthlyRevenue: 720000,
    monthlyCosts: 324000,
    cumulativeCostsSinceInception: 9900000,
    mostRecentProjectCost: 440000,
    pipelineValue: 280000,
    pipelineStatus: "negotiating",
    industry: "Investment Banking",
    sector: "Sell-Side",
    accountStatus: "active",
  },
  {
    id: "36",
    name: "Raymond James",
    headcount: 10,
    headcountUS: 9,
    headcountIndia: 1,
    monthlyRevenue: 680000,
    monthlyCosts: 306000,
    cumulativeCostsSinceInception: 9200000,
    mostRecentProjectCost: 390000,
    pipelineValue: 300000,
    pipelineStatus: "closing",
    industry: "Investment Banking",
    sector: "Sell-Side",
    accountStatus: "active",
  },
  {
    id: "37",
    name: "Lincoln Financial",
    headcount: 9,
    headcountUS: 6,
    headcountIndia: 3,
    monthlyRevenue: 450000,
    monthlyCosts: 680000,
    cumulativeCostsSinceInception: 10200000,
    mostRecentProjectCost: 280000,
    pipelineValue: 0,
    pipelineStatus: "none",
    industry: "Life Insurance",
    sector: "Insurance",
    accountStatus: "inactive",
  },
  {
    id: "38",
    name: "Ameriprise",
    headcount: 14,
    headcountUS: 9,
    headcountIndia: 5,
    monthlyRevenue: 920000,
    monthlyCosts: 414000,
    cumulativeCostsSinceInception: 13400000,
    mostRecentProjectCost: 610000,
    pipelineValue: 0,
    pipelineStatus: "none",
    industry: "Wealth & AM",
    sector: "Asset Management",
    accountStatus: "active",
  },
  {
    id: "39",
    name: "CNA Financial",
    headcount: 12,
    headcountUS: 7,
    headcountIndia: 5,
    monthlyRevenue: 780000,
    monthlyCosts: 351000,
    cumulativeCostsSinceInception: 11100000,
    mostRecentProjectCost: 460000,
    pipelineValue: 200000,
    pipelineStatus: "negotiating",
    industry: "P&C Insurance",
    sector: "Insurance",
    accountStatus: "active",
  },
  {
    id: "40",
    name: "Aon",
    headcount: 17,
    headcountUS: 11,
    headcountIndia: 6,
    monthlyRevenue: 1100000,
    monthlyCosts: 495000,
    cumulativeCostsSinceInception: 16200000,
    mostRecentProjectCost: 740000,
    pipelineValue: 320000,
    pipelineStatus: "early",
    industry: "Insurance Brokerage",
    sector: "Insurance",
    accountStatus: "active",
  },
];

export const expenses: Expense[] = [
  { id: "e1", category: "Personnel", description: "Executive Salaries", amount: 850000, type: "company" },
  { id: "e2", category: "Personnel", description: "HR & Admin Staff", amount: 320000, type: "company" },
  { id: "e3", category: "Facilities", description: "HQ Office Lease", amount: 185000, type: "company" },
  { id: "e4", category: "Facilities", description: "Regional Offices", amount: 95000, type: "company" },
  { id: "e5", category: "Technology", description: "Internal IT Infrastructure", amount: 125000, type: "company" },
  { id: "e6", category: "Technology", description: "Software Licenses", amount: 78000, type: "company" },
  { id: "e7", category: "Operations", description: "Insurance & Legal", amount: 145000, type: "company" },
  { id: "e8", category: "Operations", description: "Training & Development", amount: 65000, type: "company" },
  { id: "e9", category: "Marketing", description: "Brand & Advertising", amount: 210000, type: "company" },
  { id: "e10", category: "Marketing", description: "Events & Conferences", amount: 85000, type: "company" },

  { id: "ce1", category: "Travel", description: "On-site Consulting", amount: 45000, type: "customer", customerId: "1" },
  { id: "ce2", category: "Technology", description: "Dedicated Infrastructure", amount: 32000, type: "customer", customerId: "1" },
  { id: "ce3", category: "Travel", description: "Client Meetings", amount: 28000, type: "customer", customerId: "2" },
  { id: "ce4", category: "Technology", description: "Custom Development Tools", amount: 55000, type: "customer", customerId: "6" },
  { id: "ce5", category: "Personnel", description: "Dedicated Account Team", amount: 120000, type: "customer", customerId: "14" },
  { id: "ce6", category: "Travel", description: "Executive Visits", amount: 18000, type: "customer", customerId: "3" },
  { id: "ce7", category: "Technology", description: "Security Compliance", amount: 42000, type: "customer", customerId: "8" },
  { id: "ce8", category: "Operations", description: "Compliance Audits", amount: 35000, type: "customer", customerId: "21" },
  { id: "ce9", category: "Travel", description: "Training Delivery", amount: 22000, type: "customer", customerId: "5" },
  { id: "ce10", category: "Technology", description: "API Integration Support", amount: 38000, type: "customer", customerId: "9" },
];

export const getTotalHeadcount = () => customers.reduce((sum, c) => sum + c.headcount, 0);
export const getTotalRevenue = () => customers.reduce((sum, c) => sum + c.monthlyRevenue, 0);
export const getTotalCosts = () => customers.reduce((sum, c) => sum + c.monthlyCosts, 0);
export const getTotalPipeline = () => customers.reduce((sum, c) => sum + c.pipelineValue, 0);
export const getCompanyExpenses = () =>
  expenses.filter((e) => e.type === "company").reduce((sum, e) => sum + e.amount, 0);
export const getCustomerExpenses = () =>
  expenses.filter((e) => e.type === "customer").reduce((sum, e) => sum + e.amount, 0);
